rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.AWS.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.AWS.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.AWS.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.AWS.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Exchange.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Exchange.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Exchange.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Exchange.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Ancora.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Ancora.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Ancora.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Ancora.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.ExtractFromWeb.Design /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.ExtractFromWeb.Design /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.ExtractFromWeb.Design /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.ExtractFromWeb.Design /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Runtime.Engine /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Runtime.Engine /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Runtime.Engine /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Runtime.Engine /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Services.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Services.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Services.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Services.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Core /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Core /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Core /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Core /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.XML.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.XML.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.XML.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.XML.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.CaptureFast.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.CaptureFast.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.CaptureFast.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.CaptureFast.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.UIAutomation.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.UIAutomation.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.UIAutomation.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.UIAutomation.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.FTP.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.FTP.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.FTP.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.FTP.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.File.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.File.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.File.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.File.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Folder.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Folder.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Folder.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Folder.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\WinAutomation.Localization /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\WinAutomation.Localization /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\WinAutomation.Localization /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\WinAutomation.Localization /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.DateTime.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.DateTime.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.DateTime.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.DateTime.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.UIAutomation.UI.Common /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.UIAutomation.UI.Common /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.UIAutomation.UI.Common /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.UIAutomation.UI.Common /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.OCR.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.OCR.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.OCR.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.OCR.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.OCR.Utilities /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.OCR.Utilities /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.OCR.Utilities /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.OCR.Utilities /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Excel.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Excel.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Excel.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Excel.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Display.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Display.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Display.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Display.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Variables.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Variables.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Variables.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Variables.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Console.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Console.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Console.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Console.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Cmd.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Cmd.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Cmd.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Cmd.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.MouseAndKeyboard.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.MouseAndKeyboard.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.MouseAndKeyboard.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.MouseAndKeyboard.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Cryptography.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Cryptography.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Cryptography.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Cryptography.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Web.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Web.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Web.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Web.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.ActiveDirectory.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.ActiveDirectory.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.ActiveDirectory.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.ActiveDirectory.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Azure.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Azure.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Azure.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Azure.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Database.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Database.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Database.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Database.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.MacroRecorder.Driver /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.MacroRecorder.Driver /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.MacroRecorder.Driver /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.MacroRecorder.Driver /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Clipboard.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Clipboard.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Clipboard.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Clipboard.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.TerminalEmulation.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.TerminalEmulation.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.TerminalEmulation.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.TerminalEmulation.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Text.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Text.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Text.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Text.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Cyberark.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Cyberark.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Cyberark.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Cyberark.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.MacroRecorder.Application /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.MacroRecorder.Application /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.MacroRecorder.Application /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.MacroRecorder.Application /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.System.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.System.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.System.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.System.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.CompressionOpenSource.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.CompressionOpenSource.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.CompressionOpenSource.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.CompressionOpenSource.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.MacroRecorder.UI /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.MacroRecorder.UI /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.MacroRecorder.UI /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.MacroRecorder.UI /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Cognitive.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Cognitive.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Cognitive.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Cognitive.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Email.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Email.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Email.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Email.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.WebAutomation.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.WebAutomation.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.WebAutomation.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.WebAutomation.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.Outlook.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.Outlook.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.Outlook.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.Outlook.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Modules.PDF.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Modules.PDF.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Modules.PDF.Actions /s /q
rd f:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Modules.PDF.Actions /s /q
