C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Engine\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.ExtractFromWeb.Design\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.MacroRecorder.Application\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.MacroRecorder.Driver\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.MacroRecorder.UI\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.ActiveDirectory.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Ancora.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.AWS.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Azure.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.CaptureFast.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Clipboard.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Cmd.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Cognitive.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Compression.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.CompressionOpenSource.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Console.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Cryptography.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Cyberark.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Database.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.DateTime.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Display.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Email.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Excel.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Exchange.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.File.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Folder.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.FTP.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.MouseAndKeyboard.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.OCR.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.OCR.Utilities\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.OpenFtp.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Outlook.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.PDF.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Services.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.System.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.TerminalEmulation.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Text.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.UIAutomation.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Variables.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.Web.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.WebAutomation.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Modules.XML.Actions\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Runtime.Agent\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Runtime.Robot\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.SDK\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Shared.Runtime.WatiNLib\WatiN.Core\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.UIAutomation.UI.Common\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\WinAutomation.Localization\Properties\Resources.resx.lcg
C:\Repo\power-platform-loc\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\WinAutomation.Localization\Properties\Supplement.resx.lcg