test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.AWS.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.AWS.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.AWS.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.AWS.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Exchange.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Exchange.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Exchange.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Exchange.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Ancora.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Ancora.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Ancora.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Ancora.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\UIAutomation.ExtractFromWeb\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\UIAutomation.ExtractFromWeb\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\UIAutomation.ExtractFromWeb\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\UIAutomation.ExtractFromWeb\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.Engine\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.Engine\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.Engine\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.Engine\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Services.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Services.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Services.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Services.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Robin.SDK\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Robin.SDK\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Robin.SDK\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Robin.SDK\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.XML.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.XML.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.XML.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.XML.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.CaptureFast.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.CaptureFast.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.CaptureFast.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.CaptureFast.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.UIAutomation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.UIAutomation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.UIAutomation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.UIAutomation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.FTP.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.FTP.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.FTP.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.FTP.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.File.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.File.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.File.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.File.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Folder.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Folder.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Folder.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Folder.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Shared.Localization\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Shared.Localization\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Shared.Localization\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Shared.Localization\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.DateTime.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.DateTime.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.DateTime.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.DateTime.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\UIAutomation.Recorder.UI\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\UIAutomation.Recorder.UI\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\UIAutomation.Recorder.UI\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\UIAutomation.Recorder.UI\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.OCR.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.OCR.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.OCR.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.OCR.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.OCR.Utilities\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.OCR.Utilities\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.OCR.Utilities\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.OCR.Utilities\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Excel.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Excel.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Excel.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Excel.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Display.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Display.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Display.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Display.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Variables.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Variables.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Variables.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Variables.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Console.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Console.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Console.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Console.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Cmd.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Cmd.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Cmd.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Cmd.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.MouseAndKeyboard.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.MouseAndKeyboard.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.MouseAndKeyboard.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.MouseAndKeyboard.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Cryptography.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Cryptography.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Cryptography.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Cryptography.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Web.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Web.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Web.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Web.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.ActiveDirectory.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.ActiveDirectory.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.ActiveDirectory.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.ActiveDirectory.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Azure.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Azure.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Azure.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Azure.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Database.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Database.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Database.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Database.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.Driver\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.Driver\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.Driver\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.Driver\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Clipboard.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Clipboard.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Clipboard.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Clipboard.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.TerminalEmulation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.TerminalEmulation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.TerminalEmulation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.TerminalEmulation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Text.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Text.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Text.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Text.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Cyberark.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Cyberark.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Cyberark.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Cyberark.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.Application\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.Application\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.Application\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.Application\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.System.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.System.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.System.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.System.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Compression.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Compression.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Compression.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Compression.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.UI\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.UI\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.UI\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.UI\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Cognitive.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Cognitive.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Cognitive.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Cognitive.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Email.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Email.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Email.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Email.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.WebAutomation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.WebAutomation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.WebAutomation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.WebAutomation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Outlook.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Outlook.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Outlook.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Outlook.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-CA\Flow-PeopleBot\src\Modules.Pdf.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\en-US\Flow-PeopleBot\src\Modules.Pdf.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-CA\Flow-PeopleBot\src\Modules.Pdf.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Adaptation\PowerAutomate\PAuFlowPeopleBot\fr-FR\Flow-PeopleBot\src\Modules.Pdf.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.AWS.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.AWS.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.AWS.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.AWS.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Exchange.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Exchange.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Exchange.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Exchange.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Ancora.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Ancora.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Ancora.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Ancora.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\UIAutomation.ExtractFromWeb\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\UIAutomation.ExtractFromWeb\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\UIAutomation.ExtractFromWeb\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\UIAutomation.ExtractFromWeb\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Robin.Engine\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.Engine\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Robin.Engine\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Robin.Engine\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Services.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Services.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Services.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Services.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Robin.SDK\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Robin.SDK\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Robin.SDK\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Robin.SDK\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.XML.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.XML.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.XML.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.XML.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.CaptureFast.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.CaptureFast.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.CaptureFast.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.CaptureFast.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.UIAutomation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.UIAutomation.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.UIAutomation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.UIAutomation.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.FTP.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.FTP.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.FTP.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.FTP.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.File.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.File.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.File.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.File.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Folder.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Folder.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Folder.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Folder.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Shared.Localization\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Shared.Localization\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Shared.Localization\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Shared.Localization\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.DateTime.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.DateTime.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.DateTime.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.DateTime.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\UIAutomation.Recorder.UI\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\UIAutomation.Recorder.UI\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\UIAutomation.Recorder.UI\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\UIAutomation.Recorder.UI\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.OCR.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.OCR.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.OCR.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.OCR.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.OCR.Utilities\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.OCR.Utilities\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.OCR.Utilities\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.OCR.Utilities\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Excel.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Excel.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Excel.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Excel.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Display.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Display.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Display.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Display.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Variables.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Variables.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Variables.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Variables.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Console.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Console.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Console.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Console.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Cmd.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Cmd.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Cmd.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Cmd.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.MouseAndKeyboard.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.MouseAndKeyboard.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.MouseAndKeyboard.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.MouseAndKeyboard.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Cryptography.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Cryptography.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Cryptography.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Cryptography.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Web.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Web.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Web.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Web.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.ActiveDirectory.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.ActiveDirectory.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.ActiveDirectory.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.ActiveDirectory.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Azure.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Azure.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Azure.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Azure.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Database.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Database.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Database.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Database.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.Driver\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.Driver\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.Driver\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.Driver\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Clipboard.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Clipboard.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Clipboard.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Clipboard.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.TerminalEmulation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.TerminalEmulation.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.TerminalEmulation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.TerminalEmulation.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Text.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Text.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Text.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Text.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Cyberark.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Cyberark.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Cyberark.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Cyberark.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.Application\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.Application\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.Application\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.Application\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.System.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.System.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.System.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.System.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Compression.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Compression.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Compression.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Compression.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.UI\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.UI\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.UI\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\UIAutomation.DesktopRecorder.UI\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Cognitive.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Cognitive.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Cognitive.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Cognitive.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Email.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Email.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Email.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Email.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.WebAutomation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.WebAutomation.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.WebAutomation.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.WebAutomation.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Outlook.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Outlook.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Outlook.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Outlook.Actions\Properties\Resources.resx
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\ar\Flow-PeopleBot\src\Modules.Pdf.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Base\Flow-PeopleBot\src\Modules.Pdf.Actions\Properties\Resources.resx.lcg
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\he\Flow-PeopleBot\src\Modules.Pdf.Actions\Properties\Resources.resx.lcl
test-path F:\Automation\BAGIE\D365_CE\Preview\PowerAutomate\PAuFlowPeopleBot\Master\Flow-PeopleBot\src\Modules.Pdf.Actions\Properties\Resources.resx